AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  iot-shadow-lambda

  Sample SAM Template for iot-shadow-lambda

Parameters:
  BucketName:
    Type: String
    Description: bucket name to create

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15
    MemorySize: 5312

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        BucketEvent:
          Type: S3
          Properties:
            Bucket: !Ref IoTBucket
            Events: # https://docs.aws.amazon.com/AmazonS3/latest/userguide/notification-how-to-event-types-and-destinations.html
              - 's3:ObjectCreated:*'
      Policies:
        - Statement:
          - Sid: S3Get 
            Effect: Allow
            Action:
            - s3:GetObject
            Resource:
            - !Sub arn:aws:s3:::${BucketName}/*
         
          - Sid: IoT
            Effect: Allow
            Action:
            - iot:ListThings
            - iot:GetThingShadow
            - iot:UpdateThingShadow
            Resource:
            - "*"

  IoTBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
